//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        public empresas()
        {
            this.produtos_empresa = new HashSet<produtos_empresa>();
        }
    
        public int idEmpresa { get; set; }
        public string nmEmpresa { get; set; }
        public string dsCNPJ { get; set; }
        public string dsEndereco { get; set; }
        public bool flAtivo { get; set; }
    
        public virtual ICollection<produtos_empresa> produtos_empresa { get; set; }
    }
}
