//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos
    {
        public int idProduto { get; set; }
        public int idGrupo { get; set; }
        public string nmProduto { get; set; }
        public string dsProdutos { get; set; }
        public bool flAtivo { get; set; }
        public Nullable<bool> flEstoque { get; set; }
    
        public virtual grupos_produto grupos_produto { get; set; }
    }
}
