//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos_empresa
    {
        public int idProduto { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual empresas empresas { get; set; }
    }
}
