//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteManager.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class artfocalEntities : DbContext
    {
        public artfocalEntities()
            : base("name=artfocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<empresas> empresas { get; set; }
        public DbSet<grupos_produto> grupos_produto { get; set; }
        public DbSet<imagens> imagens { get; set; }
        public DbSet<produtos> produtos { get; set; }
        public DbSet<produtos_empresa> produtos_empresa { get; set; }
        public DbSet<produtos_imagens> produtos_imagens { get; set; }
    }
}
